# Generated by Django 3.2.8 on 2021-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.DecimalField(decimal_places=3, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
