# Generated by Django 3.2.9 on 2021-11-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(default='plant1', max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('level', models.IntegerField(default=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plant_type', models.CharField(max_length=20)),
            ],
        ),
    ]
