# Generated by Django 3.2.9 on 2021-11-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiAssignment2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moisture',
            name='name',
        ),
    ]
