# Generated by Django 3.2.8 on 2021-10-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAssignment2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moisture',
            name='level',
            field=models.IntegerField(default=50),
        ),
    ]
